apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: container-server
        image: model-server:default
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /model?minutes=5
            port: 5000
            host: localhost
        readinessProbe:
          httpGet:
            path: /model?minutes=5
            port: 5000
            host: localhost
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: model-config
              key: path
        volumeMounts:
        - name: model-volume
          mountPath: /model
      volumes:
      - name: model-volume
        hostPath:
          path: /tmp

