apiVersion: batch/v1
kind: Job
metadata:
  name: model-train
spec:
  template:
    spec:
      containers:
      - name: container-train
        image: model-train:default
        # command: []
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: model-config
              key: path
        volumeMounts:
        - name: model-volume
          mountPath: /model
      volumes:
      - name: model-volume
        hostPath:
          path: /tmp
      restartPolicy: Never
  backoffLimit: 4



